### PR TITLE
Jump back to agenda after clocking

### PR DESCRIPTION
**Pull request by paretje**
Currently, after clocking a headline, you've left the preview window with the agenda.

### CODE REVIEW

**Comment by dhruvasagar** [comment]
The thing is this function may be called from within the agenda window too, as well as from within a dotoo file. Jumping back is a very specific use case I believe and does not belong here.

**Comment by paretje** [comment]
Well, that's what it does, it jumps back to the agenda, as the agenda is a preview window. I must admit I forgot about the dotoo file. Would you accept it when it would only do this when coming from the agenda?

**Comment by dhruvasagar** [comment]
Perhaps, but there is a likelygood that the agenda is closed, or worse that the preview window isn't even our agendaview, so we'd have to take those conditions into account.

I still believe this belongs perhaps to the ftplugin maybe.

Can you explain your complete workflow ?

**Comment by paretje** [comment]
It should be in the ftplugin indeed, as it's only applicable when you run this from the agenda. I jump now to the previous window, on the condition it's the agenda.

It isn't part of my current workflow, yet. I was trying it out, and expected to just be able to continue in the agenda view, or maybe even that the agenda view would be closed.

**Pull request merged**
