### PR TITLE
Don't show done items in todo list

### PR DESCRIPTION
**Pull request by paretje**
Currently, in the todo view of the agenda, all items are shown, including those marked as done. I changed this to show only items which are still active.

### CODE REVIEW

**Comment by dhruvasagar** [comment]
This was done intentionally, if you remove the DONE items from this list, then there is no way to look at the DONE items ever. I recommend using filters instead to remove done items perhaps, what do you think ?

**Comment by paretje** [comment]
Maybe it depends on your workflow, but when I open the todo view, it's to have a clear view on what's left for me to do. In fact, I would like to have, above the items currently shown on the todo list, items with a deadline (not scheduled).

**Comment by dhruvasagar** [comment]
Will think a bit about this tomorrow. Need to give this some thought.

**Comment by paretje** [comment]
Maybe I should explain myself: the way I see it, the todo view should contain what's left todo, so definitely no things which are done or cancelled. You may want to see done items occasionally, but then you simply open the relevant file, or use git, to go back in time. Concerning showing scheduled or deadline todo items, it depends on what you want it to be:
 - if you want it to be a list of things which can't be put somehow on the calendar, then the current situation is perfect (well, except it does include done items)
 - if you want it to be a list of things you haven't scheduled yet, show above the current items the items with a deadline, but which aren't scheduled at a future time
 - if you want it to be a list of things you have to do, show everything, in three sections

Personally, I would prefer the second scenario, I think, as it would somehow encourage yourself to schedule things you've got to do.

**Comment by dhruvasagar** [comment]
I think it does make sense, although I think I might have a separate view perhaps to see what was done, when. It makes sense to have it as a separate view altogether.

Thanks for your contributions :). Any comments on the code ?

**Comment by paretje** [comment]
Seems a good idea indeed, as it provides a way to reflect on your recent productivity. I should however note that I've realized the conclusion I did in my last post is wrong, as scheduled items stay on the agenda until they're marked done.

I think the code is quite clear and easy to work with. I have discovered some bugs, which I'll fix or/and report. I've written the needed code to toggle checkboxes, but before I do a pull request, I'll update it to update progress indications.

It's not really the right place to discuss this, but I wonder what's the main reason you defined your own custom readfile function, instead of using vim's. Anyway, the need for `set hidden` should probably be more documented.

**Comment by dhruvasagar** [comment]
All valid points, the custom readline is to allow for reading files in the background with set hidden, because that helps the overall working of the plugin, for persistance of changes. The native vim readline, as opposed to my initial belief, does not load the file in vim.

**Pull request merged**
