### PR TITLE
Support for embedded latex conceal

### PR DESCRIPTION
**Pull request by Gavinok**
When using `$latex math$` or `$$ latex math $$` the conceal properties that usually apply to .tex files is used within the block. This is meant to mimic the latex preview feature from org mode.

### CODE REVIEW

**Comment by Gavinok** [comment]
forgot to mention that it follows your g:tex_conceal setting so if you dont want any concealing you could just do let g:tex_conceal="" for none and let g:tex_conceal="abdgm" for all tex concealing.

**Comment by Gavinok** [comment]
I realized that this could also be achieved using SyntaxRea

**Comment by dhruvasagar** [comment]
@Gavinok Interesting, I notice the changes you pushed don't seem to have anything to do with latex syntax embedding though. But I kinda have a partially done version of the capture file option somewhere that I can work on and push.

As far as the support for embedded syntax goes, `:h syn-include` is likely the one you want to use, however even for that I would like to do this based on some global configuration, such as ```vim
g:dotoo_included_languages = [
    \ 'latex'
    \ ]
```
That would make it flexible to allow us to add more embedded languages in the future while at the same time won't be enabled by default. Embedded syntaxes can have performance issues based on the language you're embedding.

Thanks for your contribution, it's nice to see this project is being used, that motivates me to put more effort into it. Also thanks for your support on open collective.

**Comment by Gavinok** [comment]
My mistake I accidentally pushed from the wrong branch. This branch was for expanding the capture functionality. The code I was working on used synax include. you make a good point when it comes to adding this for other languages.

**Pull request closed without merging**
