### PR TITLE
Feature/refile target

### PR DESCRIPTION
**Pull request by dhruvasagar**
Improve Capture functionality

* More customizable capture templates
* Add support for specifying targets for capture templates, this is useful if you want a capture template to go to a specific file / headline instead of the refile file.

### CODE REVIEW

**Comment by dhruvasagar** [comment]
@Gavinok Let me know your thoughts regarding this.

**Comment by dhruvasagar** [comment]
@Gavinok I am going ahead and merging this, seems to be working fine as per my tests I am also planning on adding a lot more unit tests gradually. Let me know your thoughts about this when you find time.

**Comment by Gavinok** [comment]
@dhruvasagar I gave it a try and it seems to work however I can't seem to get my custom template to work. Everytime I use gC my setting for g:dotoo#capture#template gets over written. Any idea what might be happening?

**Comment by dhruvasagar** [comment]
@Gavinok how and what do you set it to ?

**Comment by dhruvasagar** [comment]
@Gavinok well I tested with the following : 

With that I was able to override and provide my own custom template. Note however, this generates just a todo, without a deadline so that is not shown under agenda (agenda displays those that have a deadline). But that you can always add.

```vim
let g:dotoo#capture#templates = {
      \ 't' : {
      \   'lines': [
      \     '* TODO is good %? headline with :tag:'
      \   ],
      \ }
      \}
```

**Comment by Gavinok** [comment]
With these settings it says my setting for g:dotoo#capture#templates is what it should be but as soon as I run gC it changes back to the default.
```
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
	Plug 'dhruvasagar/vim-dotoo'
call plug#end()
let g:dotoo#capture#templates = {
      \ 't' : {
      \   'lines': [
      \     '* TODO is good %? headline with :tag:'
      \   ],
      \ }
      \}

```

**Comment by dhruvasagar** [comment]
@Gavinok Can you try moving the `let g:dotoo#capture#templates` to before the plug block where you add plugins ?

**Comment by Gavinok** [comment]
I still seems to overwright these settings.
dotooissue

**Comment by dhruvasagar** [comment]
What version of vim do you have ? I hope you're on the latest version. I added piece of code to do a merge, but i'll look at that again and try to cover more scenarios. Ideally the setting gets defined in your vimrc and once you invoke capture, it then tries to do a nested merge with the defaults set in capture.

**Comment by dhruvasagar** [comment]
@Gavinok ^

**Comment by Gavinok** [comment]
Im running NVIM v0.4.3

**Comment by dhruvasagar** [comment]
@Gavinok interesting, I testede on nvim 0.5.0-nightly-1467-g5f9209389, and it seems to be working.
When you open vim `:echo g:dotoo#capture#templates` should look like this `{'lines': ['* todo is good %? headline with :tag:']}` based on what you define in vimrc, however once you hit <kbd>gC</kbd> it should then be `{'target': 'refile:Tasks', 'description': 'Todo', 'lines': ['* todo is good %? headline with :tag:']}`, effectively merging properly overriding the template lines.

**Comment by dhruvasagar** [comment]
@Gavinok the gif goes by too fast, I am not able to notice, but I think it should have merged it like I said above, the point to note is that the key `'t'` contents would be the ones affected and if you look at the `'lines'` within it, that should be showing your changed configuration and not what's the default set by vim-dotoo.

**Comment by dhruvasagar** [comment]
@Gavinok I was successfully able to convert the gif to video and pause it, it looks good, the template for todo is what you configure in your vimrc.

**Comment by Gavinok** [comment]
I think i get what you mean now its not currently working in my current setup but it did change the settings for `t`. My mistake,  I missunderstood the docs. I still am having issues getting this to work with my current config.

**Comment by Gavinok** [comment]
Figured it out seems to work besides adding new templates but its probably somthing on my end.

**Comment by dhruvasagar** [comment]
@Gavinok No that is how it's designed to work, your vimrc config is only overriding a specific template (todo), but there are others that are provided by default, capture plugin adds those.

**Comment by dhruvasagar** [comment]
@Gavinok ah I think I misunderstood. Let me know, should work for adding based on my tests.

**Pull request merged**
